export const BUY_LAPTOP="BUY-LAPTOP";
export const BUY_MOBILE="BUY-MOBILE";

 export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";
